language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

# Uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false


#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("AIBECS"); Pkg.test("AIBECS"; coverage=true)';

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("AIBECS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg; cd(Pkg.dir("AIBECS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: linux
      before_script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.add("Conda"); using Conda;
                                    Conda.add("matplotlib"); Conda.add("cartopy")';
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.add("PyCall"); ENV["PYTHON"]=""; Pkg.build("PyCall")' 
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
